import { Injectable } from '@angular/core';
import { Book } from '../model/book';

@Injectable({
  providedIn: 'root'
})
export class BookService {

  private books = new Array<Book>();
  private bookAutoId = 0;

  constructor() { }

  save(){

    localStorage.setItem('books', JSON.stringify(this.books));
    localStorage.setItem('bookAutoGeneratedId', this.bookAutoId.toString());

  }

  load(){

    this.books = JSON.parse(localStorage.getItem('books'));

    if (this.books == null) {
      this.books = new Array<Book>();
    }

    const autoId = localStorage.getItem('bookAutoGeneratedId');

    if (autoId) {
      this.bookAutoId = Number(autoId);
    }

  }

  insert(book: Book){

    book.id = this.bookAutoId;
    this.books.push(book);
    this.bookAutoId++;

    this.save();

  }

  list(): Array<Book> {

    this.load();
    return this.books;

  }

  remove (id: number) {

    for (let i = 0; i < this.books.length; i++) {

      const b = this.books[i];

      if (b.id === id) {

        this.books.splice(i,1);
        break;

      }
    }

    this.save();

  }

  update(book: Book) {

    for(let i = 0; i < this.books.length; i++) {

      const bo = this.books[i];

      if (bo.id === book.id){

        this.books[i] = book;
        break;

      }

    }

    this.save();

  }


}
