import { Injectable } from '@angular/core';
import { Categoria } from '../model/book_categoria';

@Injectable({
  providedIn: 'root'
})
export class CategoriaService {

  private categorias = new Array<Categoria>();
  private categoriaAutoId = 0;

  constructor() { }

  save(){

    localStorage.setItem('categorias', JSON.stringify(this.categorias));
    localStorage.setItem('categoriaAutoGeneratedId', this.categoriaAutoId.toString());

  }

  load(){

    this.categorias = JSON.parse(localStorage.getItem('categorias'));

    if (this.categorias == null) {
      this.categorias = new Array<Categoria>();
    }

    const autoId = localStorage.getItem('categoriaAutoGeneratedId');

    if (autoId) {
      this.categoriaAutoId = Number(autoId);
    }

  }

  insert(categoria: Categoria){

    categoria.id = this.categoriaAutoId;
    this.categorias.push(categoria);
    this.categoriaAutoId++;

    this.save();

  }

  list(): Array<Categoria> {

    this.load();
    return this.categorias;

  }

  remove (id: number) {

    for (let i = 0; i < this.categorias.length; i++) {

      const b = this.categorias[i];

      if (b.id === id) {

        this.categorias.splice(i,1);
        break;

      }
    }

    this.save();

  }

  update(categoria: Categoria) {

    for(let i = 0; i < this.categorias.length; i++) {

      const bo = this.categorias[i];

      if (bo.id === categoria.id){

        this.categorias[i] = categoria;
        break;

      }

    }

    this.save();

  }


}
