import { Injectable } from '@angular/core';
import { Game } from '../model/game';

@Injectable({
  providedIn: 'root'
})
export class GameService {

  private games = new Array<Game>();
  private autoGeneratedId = 0;

  constructor() { }


  save(){

    //salvando array no local storage convertendo para JSON
    localStorage.setItem('games', JSON.stringify(this.games));
    //Salvando o Id Geral
    localStorage.setItem('gamesAutoGeneratedId', this.autoGeneratedId.toString());

  }

  load(){

    this.games = JSON.parse(localStorage.getItem('games'));
    if (this.games == null){
      this.games = new Array<Game>();
    }

    const autoId = localStorage.getItem('gamesAutoGeneratedId');
    if (autoId){
      this.autoGeneratedId = Number(autoId);
    }

  }

  insert(game: Game){
    game.id = this.autoGeneratedId;
    this.games.push(game);
    this.autoGeneratedId++;

    this.save();
  }

  list(): Array<Game> {
    this.load();

    return this.games;

  }

  remove(id: number){
    for(let i = 0; i < this.games.length; i++){
      const jogo = this.games[i];

      if(jogo.id === id){
        this.games.splice(i, 1);
        break;
      }
    }
    this.save();
  }

  update(game: Game){
    for(let i =0; i < this.games.length; i++){
      const newGame = this.games[i];
      if(newGame.id === game.id){
        this.games[i] = game;
        break;
      }
    }
    this.save();
  }

}
