import { Injectable } from '@angular/core';
import { Genre } from '../model/genre';

@Injectable({
  providedIn: 'root'
})
export class GenreService {

  private genres = new Array<Genre>();
  private autoGeneratedGenId = 0;

  constructor() { }

  save(){

    //salvando array no local storage convertendo para JSON
    localStorage.setItem('genres', JSON.stringify(this.genres));
    //Salvando o Id Geral
    localStorage.setItem('genreAutoGeneratedGenId', this.autoGeneratedGenId.toString());

  }

  load(){

    this.genres = JSON.parse(localStorage.getItem('genres'));
    if (this.genres == null){
      this.genres = new Array<Genre>();
    }

    const autoGenId = localStorage.getItem('genreAutoGeneratedGenId');
    if (autoGenId){
      this.autoGeneratedGenId = Number(autoGenId);
    }

  }

  insert(genre: Genre){
    genre.id = this.autoGeneratedGenId;
    this.genres.push(genre);
    this.autoGeneratedGenId++;

    this.save();
  }

  list(): Array<Genre> {
    this.load();

    return this.genres;

  }

  remove(id: number){
    for(let i = 0; i < this.genres.length; i++){
      const jogo = this.genres[i];

      if(jogo.id === id){
        this.genres.splice(i, 1);
        break;
      }
    }
    this.save();
  }

  update(genre: Genre){
    for(let i =0; i < this.genres.length; i++){
      const newGame = this.genres[i];
      if(newGame.id === genre.id){
        this.genres[i] = genre;
        break;
      }
    }
    this.save();
  }

}





